import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { test } from 'node:test';
import { buildProgressDigest, parseProgressSections, readProgressContext, selectTaskDesignDocs, stripProgressDigest, upsertProgressDigest, writeProgressDigest } from '../src/context.js';
import { resolvePaths } from '../src/paths.js';
import { generateIndex, readIndexCapped, writeIndex } from '../src/repomap.js';

function project(): ReturnType<typeof resolvePaths> {
  const dir = mkdtempSync(join(tmpdir(), 'symphony-context-'));
  const paths = resolvePaths(dir);
  mkdirSync(join(paths.docs, 'design', 'adr'), { recursive: true });
  mkdirSync(paths.tasksDir, { recursive: true });
  mkdirSync(join(dir, 'src'), { recursive: true });
  return paths;
}

test('progress digest: sections are parsed, summarised and written back in place', () => {
  const text = [
    '# Progress notes',
    '',
    'Shared notebook.',
    '',
    '## T01 — First task',
    '- test command is `npm test`',
    '- uses sqlite',
    '',
    '## T02 — Second task',
    'Did the second thing without bullets.',
    '',
  ].join('\n');

  const sections = parseProgressSections(text);
  assert.deepEqual(sections.map((s) => s.heading), ['T01 — First task', 'T02 — Second task']);

  const digest = buildProgressDigest(text);
  assert.match(digest, /## Key facts \(maintained by symphony/);
  assert.match(digest, /- \*\*T01 — First task\*\*: test command is `npm test`; uses sqlite/);
  assert.match(digest, /- \*\*T02 — Second task\*\*: Did the second thing without bullets\./);

  const once = upsertProgressDigest(text, digest);
  assert.match(once, /symphony:digest:start/);
  const twice = upsertProgressDigest(once, digest);
  assert.equal(twice, once, 'upsert is idempotent');
  assert.equal(stripProgressDigest(once).includes('Key facts'), false, 'digest is stripped before parsing');

  const path = join(project().docs, 'PROGRESS.md');
  writeFileSync(path, text);
  assert.equal(writeProgressDigest(path), true);
  assert.match(readFileSync(path, 'utf8'), /Key facts/);
  assert.equal(writeProgressDigest(path), false, 'a second write is a no-op');
});

test('readProgressContext keeps the digest and only the newest sections', () => {
  const paths = project();
  const body = ['# Progress notes', ''];
  for (let i = 1; i <= 6; i++) body.push(`## T0${i} — Task ${i}`, `- fact ${i}`, '');
  writeFileSync(paths.progress, body.join('\n'));

  const out = readProgressContext(paths.progress, 'docs/PROGRESS.md', { recentSections: 2, maxBytes: 4096 });
  assert.match(out, /- \*\*T01 — Task 1\*\*: fact 1/, 'digest covers every section');
  assert.match(out, /last 2 of 6 sections/);
  assert.match(out, /## T05 — Task 5/);
  assert.match(out, /## T06 — Task 6/);
  assert.doesNotMatch(out, /## T04 — Task 4/, 'older full sections are dropped');

  const noDigest = readProgressContext(paths.progress, 'docs/PROGRESS.md', { digest: false });
  assert.doesNotMatch(noDigest, /Key facts/);
});

test('selectTaskDesignDocs inlines only the design docs the task names', () => {
  const paths = project();
  writeFileSync(join(paths.designDir, 'overview.md'), '# Overview\n\nSystem shape.\n');
  writeFileSync(join(paths.designDir, 'adr', '0001-choice.md'), '# 0001 — Choice\n');
  writeFileSync(join(paths.tasksDir, '01-thing.md'), '# T01\n');
  const body = '## Context\n- `docs/design/overview.md` — the design\n- `docs/design/adr/0001-choice.md`\n- `docs/tasks/01-thing.md` (not a design doc)\n';

  const docs = selectTaskDesignDocs(paths, body);
  assert.deepEqual(docs.map((d) => d.rel), ['docs/design/overview.md', 'docs/design/adr/0001-choice.md']);
  assert.match(docs[0].content, /System shape/);
  assert.deepEqual(selectTaskDesignDocs(paths, undefined), []);
});

test('generateIndex lists design docs with summaries and source files with symbols', () => {
  const paths = project();
  writeFileSync(join(paths.designDir, 'overview.md'), '# Overview\n\nSystem shape.\n');
  writeFileSync(join(paths.root, 'src', 'app.ts'), 'export function main() {}\nexport class Widget {}\n');
  writeFileSync(join(paths.root, 'src', 'util.py'), 'def helper():\n    pass\n');

  const text = generateIndex(paths);
  assert.match(text, /## Design documents/);
  assert.match(text, /`docs\/design\/overview\.md` — Overview/);
  assert.match(text, /`src\/app\.ts` — main, Widget/);
  assert.match(text, /`src\/util\.py` — helper/);
  assert.match(text, /_Generated by symphony/);

  const first = writeIndex(paths);
  assert.equal(first.changed, true);
  assert.equal(writeIndex(paths).changed, false, 'unchanged tree → no rewrite');
  assert.match(readIndexCapped(paths.index, 16384, 'docs/INDEX.md'), /Project index/);
  assert.match(readIndexCapped(join(paths.docs, 'missing.md'), 16384, 'x'), /not generated yet/);
});
