/*
 * One-command mock run: build a throwaway project (roadmap + tasks + fake fixtures) and launch the
 * real CLI against it with the `fake` provider, so the TUI and the whole lifecycle can be exercised
 * without an LLM.
 *
 *   npm run mock                 fresh project under <repo>/.mock, then run
 *   npm run mock -- --only T01   extra args are forwarded to `run`
 *   npm run mock -- --keep      reuse the existing .mock project (keeps state + git history)
 *   npm run mock:clean           delete .mock
 *
 * `.mock/` is gitignored (see .gitignore), so nothing generated here is ever committed.
 */
import { spawn, spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const project = process.env.SYMPHONY_MOCK_DIR ? resolve(process.env.SYMPHONY_MOCK_DIR) : join(root, '.mock');

const argv = process.argv.slice(2);
const clean = argv.includes('--clean');
const keep = argv.includes('--keep');
const forward = argv.filter((a) => a !== '--clean' && a !== '--keep');

if (clean) {
  rmSync(project, { recursive: true, force: true });
  console.log(`removed ${project}`);
  process.exit(0);
}
// A fresh project each run by default; --keep preserves state.json, logs and git history.
if (!keep) rmSync(project, { recursive: true, force: true });

const docs = join(project, 'docs');
const tasks = join(docs, 'tasks');
const fixtures = join(project, '.symphony', 'fixtures');
mkdirSync(tasks, { recursive: true });
mkdirSync(join(docs, 'design', 'adr'), { recursive: true });
mkdirSync(fixtures, { recursive: true });

const result = (status, summary) =>
  JSON.stringify({ type: 'result', subtype: 'success', is_error: false, session_id: 's', result: `SYMPHONY_RESULT\nstatus: ${status}\nsummary: ${summary}\nEND_SYMPHONY_RESULT` });
const init = (id) => JSON.stringify({ type: 'system', subtype: 'init', session_id: id });
const text = (t) => JSON.stringify({ type: 'assistant', message: { content: [{ type: 'text', text: t }] } });
const write = (path, content) => JSON.stringify({ type: 'fake_write', path, content });
const sleep = (ms) => JSON.stringify({ type: 'fake_sleep', ms });
const fixture = (name, lines) => writeFileSync(join(fixtures, name), `${lines.join('\n')}\n`);

const plan = [
  ['T01', 'Mock: write a file'],
  ['T02', 'Mock: continue then finish'],
  ['T03', 'Mock: block for a human'],
  ['T04', 'Mock: final task'],
];
writeFileSync(join(docs, 'ROADMAP.md'), [
  '# Mock roadmap', '', '## Phase 1', '',
  ...plan.map(([id, title]) => `- [ ] ${id} — ${title} → [tasks/${id.slice(1)}-mock.md](tasks/${id.slice(1)}-mock.md)`),
  '',
].join('\n'));
for (const [id, title] of plan) {
  writeFileSync(join(tasks, `${id.slice(1)}-mock.md`), `# ${id} — ${title}\n\n## Goal\nDemonstrate the harness with the fake provider.\n\n## Scope\n- write a file\n\n## Done when\n- the fake fixture reports a status\n\n## Hand-off\n_(tbd)_\n`);
}
writeFileSync(join(docs, 'PROGRESS.md'), '# Progress notes\n\n## T00 — mock project\nGenerated by `npm run mock`.\n');
writeFileSync(join(docs, 'design', 'README.md'), '# Design\n\nMock design docs.\n');
writeFileSync(join(docs, 'design', 'adr', '0000-template.md'), '# ADR template\n');

// T02 reports `continue` then `done`, so its row shows per-session child lines.
fixture('T01.jsonl', [init('s1'), text('Writing the mock file…'), write('mock/T01.txt', 'T01'), sleep(1200), result('done', 'T01 wrote its file')]);
fixture('T02.task.jsonl', [init('s2'), text('First slice…'), write('mock/T02-a.txt', 'a'), sleep(900), result('continue', 'first slice landed')]);
fixture('T02.continue.jsonl', [init('s3'), text('Second slice…'), write('mock/T02-b.txt', 'b'), sleep(900), result('done', 'T02 finished')]);
fixture('T03.jsonl', [init('s4'), text('Hitting a human decision…'), sleep(900), result('blocked', 'needs a human decision')]);
fixture('T04.jsonl', [init('s5'), text('Last one…'), write('mock/T04.txt', 'T04'), sleep(900), result('done', 'T04 finished')]);

// onBlocked: continue so the demo runs every task; provider: fake so no --provider flag is needed.
writeFileSync(join(project, '.symphony', 'symphony.config.json'), `${JSON.stringify({ provider: 'fake', onBlocked: 'continue', tui: true }, null, 2)}\n`);

const git = (args) => spawnSync('git', ['-C', project, ...args], { stdio: 'ignore' });
git(['init', '-q']);
git(['config', 'user.email', 'mock@symphony']);
git(['config', 'user.name', 'symphony mock']);

const require = createRequire(import.meta.url);
let tsx;
try { tsx = pathToFileURL(require.resolve('tsx')).href; } catch { /* fall back to dist below */ }
const cli = tsx ? join(root, 'src', 'cli.ts') : join(root, 'dist', 'cli.js');
const nodeArgs = tsx ? ['--import', tsx, cli] : [cli];

console.log(`mock project: ${project}${keep ? ' (kept)' : ' (fresh)'}`);
console.log(`clean up with: npm run mock:clean`);
const child = spawn(process.execPath, [...nodeArgs, 'run', '--root', project, ...forward], {
  stdio: 'inherit',
  env: { ...process.env, SYMPHONY_FAKE_FIXTURES: fixtures },
});
child.on('exit', (code) => process.exit(code ?? 0));
